library(tidyverse)
library(ggalt)
library(ggthemes)
library(tweenr)
library(png)
library(gifski)
library(here)

# Load full NBA shot-level shot chart data, giving dataframe of all shots taken in
#   reg season in given season, 1996-97 to present (11/24/2018);
#   generated by dataAssembly_shotCharts_full.R (~47 MB)
localPath <- "C:/Users/tdtue/Dropbox/NBA_analytics/"
load(paste(localPath, "data/shotChart_fullYear_list.RData", sep=''))

# bind list of shots by year into single dataframe;
#   create field with numeric season year (year in which season starts)
df <- shotChart_fullYear_list %>%
  bind_rows() %>%
  mutate(
    year = as.numeric(substr(season_id, 1, 4))
  )

# generate summary dataframe, giving total shots, make percentage, relative freq, etc.
#   group by shot distance, by season, and by team
shotDist_yearTeamSum_df <- df %>%
  # filter(year >= 2007) %>%
  group_by(team_name,season_id,shot_distance) %>%
  summarise(
    shot_tot = n(),
    shot_make = sum(shot_made_numeric),
    shot_points = sum(shot_made_numeric*shot_value),
    
    shot_tot_2pt = sum(shot_value == 2),
    shot_tot_3pt = sum(shot_value == 3),
    shot_make_2pt = sum( (shot_value == 2) * shot_value),
    shot_make_3pt = sum( (shot_value == 3) * shot_value)
  ) %>%
  mutate(
    shot_tot_norm = shot_tot/sum(shot_tot),
    shot_makePct = shot_make / shot_tot,
    shot_pps = shot_points / shot_tot,
    year = as.numeric(substr(season_id, 1, 4))
  )

# generate summary dataframe, giving total shots, make percentage, relative freq, etc.
#   group by shot distance and by season
shotDist_yearSum_df <- df %>%
  # filter(year >= 2007) %>%
  group_by(season_id,shot_distance) %>%
  summarise(
    shot_tot = n(),
    shot_make = sum(shot_made_numeric),
    shot_points = sum(shot_made_numeric*shot_value),
    
    shot_tot_2pt = sum(shot_value == 2),
    shot_tot_3pt = sum(shot_value == 3),
    shot_make_2pt = sum( (shot_value == 2) * shot_value),
    shot_make_3pt = sum( (shot_value == 3) * shot_value)
  ) %>%
  mutate(
    shot_tot_norm = shot_tot/sum(shot_tot),
    shot_makePct = shot_make / shot_tot,
    shot_pps = shot_points / shot_tot,
    year = as.numeric(substr(season_id, 1, 4))
  )

# generate summary dataframe, giving total shots, make percentage, relative freq, etc.
#   group by shot distance
shotDist_sum_df <- df %>%
  # filter(year >= 2007) %>%
  group_by(shot_distance) %>%
  summarise(
    shot_tot = n(),
    shot_make = sum(shot_made_numeric),
    shot_points = sum(shot_made_numeric*shot_value),
    
    shot_tot_2pt = sum(shot_value == 2),
    shot_tot_3pt = sum(shot_value == 3),
    shot_make_2pt = sum( (shot_value == 2) * shot_value),
    shot_make_3pt = sum( (shot_value == 3) * shot_value)
  ) %>%
  mutate(
    shot_tot_norm = shot_tot/sum(shot_tot),
    shot_makePct = shot_make / shot_tot,
    shot_pps = shot_points / shot_tot
  )


# generate line chart of shot frequencies by distance over time
p_densityLines_largeFacet <- shotDist_yearTeamSum_df %>%
  ggplot(aes(x = shot_distance, y = shot_tot_norm)
  ) +
  geom_xspline( # generate lines (with tightly fit splines) for each team
    aes(group = team_name),
    spline_shape=0.3, alpha = .1
  ) +
  geom_xspline( # generate single line for avg across all NBA seasons ('99 to present)
    data = shotDist_sum_df,
    spline_shape=0.3, alpha = 1, size = 1, color = 'black') +
  geom_xspline( # generate lines for season-specific 
    data = shotDist_yearSum_df,
    spline_shape=0.3, alpha = 0.9, size = 1, color = 'blue') +
  geom_xspline(
    data = shotDist_yearTeamSum_df %>%
      filter(team_name == "Houston Rockets"),
    spline_shape=0.3, alpha = 0.9, size = 1, color = 'red') +
  geom_hline(yintercept = 0, color = 'grey25') +
  geom_vline(xintercept = 0, color = 'grey25') +
  geom_vline(xintercept = c(22,23.75), color = 'grey30', linetype = 3) +
  coord_cartesian(xlim = c(0,31),
                  ylim = c(0,0.175)) +
  labs(
    x = 'Shot distance (ft)',
    y = 'Relative shot frequency',
    title = 'NBA Shot Distributions by Distance',
    subtitle = 'Charting the Origin and Spread of Moreyball',
    caption = 'Shot frequency by distance from rim, for all regular season shots.
    Small gray lines: Individual team frequencies;
    Highlighted red lines: Houston Rockets frequencies;
    Highlighted blue lines: NBA seasonal frequencies;
    Highlighted black lines: total NBA frequencies, 1999-00 through present.
    
    Source: nba.stats.com API
    By: Trevor Thomas (@VisualizingTheL, VisualizingTheLeague.com)'
  ) +
  facet_wrap(~season_id, ncol = 5) +
  theme_tufte() +
  theme(
    plot.caption = element_text(hjust = 0)
  )

# save plot to local directory
ggsave(
  plot = p_densityLines_largeFacet,
  filename = paste(localPath,
                   "graphs/shotFreq_byDist_largeFacet_NBAplusHouston.png",
                   sep = ''),
  width = 11,
  height = 8
)


#############################################################
# create animated version of shot distance distribution line chart

# start 'split' version of NBA-wide yearly average df, filtered for <= 35ft shots
#   (this step ensures that each yearly split contains an identical set of distances)
shotDist_yearSum_df_split <- shotDist_yearSum_df %>%
  ungroup() %>%
  filter(shot_distance <= 35) %>%
  mutate(
    season_id = paste('x',season_id,sep='') # add alphabetic character to avoid error in tween_states() 
  )

# split above dataframe into lists based on season ID
shotDist_yearSum_df_split <- shotDist_yearSum_df_split %>%
  split(shotDist_yearSum_df_split$season_id)

# use tweenr to develop dataframe with in-between values
shotDist_yearSum_df_tweens <- shotDist_yearSum_df_split %>%
  tween_states(3,1,'cubic-in-out',200) %>%
  mutate(
    season_id = sub('.', '', season_id), # remove leading character from season ID field
    year = as.numeric(substr(season_id, 1, 4))
  )

frames <- unique(shotDist_yearSum_df_tweens$.frame)

for(i in 1:length(frames)){
  # take subset of observed distributions ocurring for years prior to current frame
  prior_trace_df <- shotDist_yearSum_df %>%
    filter(
      year <= subset(shotDist_yearSum_df_tweens, .frame==i)$year[1],
      shot_distance <= 35
    )
  
  p <- ggplot(
    data = shotDist_yearSum_df_tweens %>% # use 'tween' df frames to plot observed distributions
      filter(.frame == i),                #    as well as between phases
    aes(x = shot_distance, y = shot_tot_norm)
  ) +
    geom_xspline(
      data = prior_trace_df,
      aes(group = season_id),
      spline_shape=0.3, alpha = 0.1, size = 0.7
    ) +
    geom_xspline(
      spline_shape=0.3, alpha = 0.9, size = 0.9, color = 'blue'
    ) +
    geom_hline(yintercept = 0, color = 'grey25') +
    geom_vline(xintercept = 0, color = 'grey25') +
    geom_vline(xintercept = c(22,23.75), color = 'grey30', linetype = 3) +
    labs(
      title = "Shot Frequency by Distance, NBA Regular Season",
      subtitle = subset(shotDist_yearSum_df_tweens, .frame==i)$season_id[1],
      x = "Shot distance from rim (ft)",
      y = "Relative shot attempt frequency",
      caption = "Source: stats.nba.api\nTrevor Thomas\nVisualizingTheLeague.com | @VisualizingTheL"
    ) +
    coord_cartesian(xlim = c(0,31),
                    ylim = c(0,0.175)) +
    theme_tufte()
  
  ggsave(
    plot = p,
    filename = paste(
      'C:/Users/tdtue/Dropbox/NBA_analytics/graphs/shot_freq_gif_frames/gif_frame_',
      str_pad(i, 3, pad = '0'),
      '.png', sep = ''
    ),
    height = 4,
    width = 6
  )
  
}

frame_dir <- 'C:/Users/tdtue/Dropbox/NBA_analytics/graphs/scrap/shot_dist_frames/'
frame_files <- list.files(frame_dir)
frame_files <- paste(frame_dir, frame_files, sep = '')
gif_file <- 'C:/Users/tdtue/Dropbox/NBA_analytics/graphs/shotDistFreq_allNBA.gif'

gifski(png_files = frame_files,
       gif_file = gif_file,
       width = 600, height = 400,
       loop = TRUE,
       delay=0.1)

utils::browseURL(gif_file)


